### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by DKanarsky** [smicallef/spiderfoot#1150] opened 2021-03-20 12:19 UTC
When building docker image it fails on python "Building wheel for cryptography"

#15 170.6     generating cffi module 'build/temp.linux-x86_64-3.6/_openssl.c'
#15 170.6     running build_rust
#15 170.6
#15 170.6         =============================DEBUG ASSISTANCE=============================
#15 170.6         If you are seeing a compilation error please try the following steps to
#15 170.6         successfully install cryptography:
#15 170.6         1) Upgrade to the latest pip and try again. This will fix errors for most
#15 170.6            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#15 170.6         2) Read https://cryptography.io/en/latest/installation.html for specific
#15 170.6            instructions for your platform.
#15 170.6         3) Check our frequently asked questions for more information:
#15 170.6            https://cryptography.io/en/latest/faq.html
#15 170.6         4) Ensure you have a recent Rust toolchain installed:
#15 170.6            https://cryptography.io/en/latest/installation.html#rust
#15 170.6         5) If you are experiencing issues with Rust for *this release only* you may
#15 170.6            set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
#15 170.6         =============================DEBUG ASSISTANCE=============================
#15 170.6
#15 170.6     error: can't find Rust compiler
#15 170.6
#15 170.6     If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
#15 170.6
#15 170.6     To update pip, run:
#15 170.6
#15 170.6         pip install --upgrade pip
#15 170.6
#15 170.6     and then retry package installation.
#15 170.6
#15 170.6     If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
#15 170.6
#15 170.6     This package requires Rust >=1.41.0.
#15 170.6
#15 170.6     ----------------------------------------

What version of SpiderFoot are you using (stable release or Git `master` branch)?
Release version 3.3

Possible workaround (as it's said in logs) is to set the environment variable CRYPTOGRAPHY_DONT_BUILD_RUST=1

**Comment by bcoles** [comment] 2021-03-20 12:31
Dupe of #1144 which I believe was fixed in #1145.

**Closed** 2021-03-27 20:04 UTC
