### ISSUE TITLE
Scans Erroring on master branch (dd28a906e11f79f4fa66dd7ffcd12602838bf40c)

### ISSUE THREAD

**Issue by mynameiswillporter** [smicallef/spiderfoot#501] opened 2020-04-09 18:22 UTC
I get the following output in the error logs:

`Unhandled exception (UnicodeEncodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/scanners/spiderfoot/sfscan.py", line 151, in startScan\n    self.ts.sf.cachePut("internet_tlds", self.ts.config[\'_internettlds\'])\n', '  File "/scanners/spiderfoot/sflib.py", line 430, in cachePut\n    fp.write(line)\n', "UnicodeEncodeError: 'ascii' codec can't encode character '\\xe9' in position 1: ordinal not in range(128)\n"]`

**Comment by bcoles** [comment] 2020-04-09 18:24
This is probably a dupe of #497 which is a dupe of #482

**Comment by smicallef** [comment] 2020-04-19 19:22
This should now be fixed. Please re-open if not.

**Closed by smicallef** 2020-04-19 19:22 UTC
