### ISSUE TITLE
"400 Bad Request - The Authorization header could not be parsed." when using empty credentials

### ISSUE THREAD

**Issue by rm1984** [smicallef/spiderfoot#1639] opened 2022-03-23 12:57 UTC
Hi,
I'm using **SpiderFoot 3.5.0** with authentication enabled.
If someone tries to login with empty username and password, he gets the following:

``
400 Bad Request

The Authorization header could not be parsed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cperror.py", line 423, in handle
    yield
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/lib/auth_digest.py", line 413, in digest_auth
    auth = HttpDigestAuthorization(
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/lib/auth_digest.py", line 215, in __init__
    raise ValueError(
ValueError: Digest Authorization header: Not all required parameters are present.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cprequest.py", line 694, in _do_respond
    self.hooks.run('before_handler')
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cprequest.py", line 95, in run
    self.run_hooks(iter(sorted(self[point])))
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cprequest.py", line 117, in run_hooks
    hook()
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cprequest.py", line 65, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/lib/auth_digest.py", line 413, in digest_auth
    auth = HttpDigestAuthorization(
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/cherrypy/_cperror.py", line 425, in handle
    raise cls(status, message or str(exc))
cherrypy._cperror.HTTPError: (400, 'The Authorization header could not be parsed.')

Powered by [CherryPy 18.6.1](http://www.cherrypy.org/)
``

this is not a real issue per se, but a simple "access denied" message would be much more elegant.

Best,
Riccardo

**Comment by bcoles** [comment] 2022-03-23 12:58
Dupe of #262

**Closed** 2022-04-04 06:23 UTC
