### ISSUE TITLE
Unexpected error during long-term scanning

### ISSUE THREAD

**Issue by 1Suprem3** [smicallef/spiderfoot#1688] opened 2022-05-28 15:54 UTC
Hello! Faced with a problem: I ran 2 scans of 2 sites, after a while I noticed that it was completed, although I understood that this could not be the case (not all goals were met). I logged into the linux server and saw this error in the console:
![image](https://user-images.githubusercontent.com/104645192/170832322-1e55915f-eabf-45d6-93c3-010d3d5d8c50.png)
(2022-05-28 01:05:22,064 [ERROR] threadpool : Error in thread worker sharedThreadPool_worker_2: Traceback (most recent call last)
File "/root/spiderfoot-4.0/spiderfoot/threadpool.py", line 256, in run'
result = callback(×args, ×*kuargs)
File "/root/spiderfoot-4.0/modules/sfp_spider.py", line 313, in handleEvent
return self.spider from(spider Target)
File "/root/spiderfoot-4.0/modules/sfp_spider.py", line 364, insider from
freshLinks = self.processUrl(link)
File "/root/spiderfoot-4.0/modules/sfp_spider.py", line 112, in process Url
if self.opts['use cookies'] and fetch['headers'] is not None:
TypeError: 'NoneType' object is not subscriptable
2022-05-28 02:04:46,205 [INFO] sf lib : Running 37 correlation rules.
2022-05-28 02:28:34,125 [INFO] sf lib : Scan [089C2113] completed.
2022-05-28 02:30:13,018 [INFO] sf lib : Scan [0E601609] completed.)
Can you tell me what could cause such errors and what are the solutions to the problem? I leave information about my system and software:
Python version used: 3.10.4
System used: Debian 11
Spiderfoot version used: 4.0
Free disk space: 100 GB
Cores/RAM: 8/12
Thanks!

**Comment by bcoles** [comment] 2022-05-28 16:09
> if self.opts['use cookies'] and fetch['headers'] is not None:

This is due to a bug in the `sfp_spider` module.

https://github.com/smicallef/spiderfoot/blob/d235402fdacbeba128796df8bbf363da1abd00d4/modules/sfp_spider.py#L100-L115

It assumes that the returned value of `sf.fetchUrl()` cannot be `None` and attempts to access the `headers` key.

Was the scan run with debugging enabled? If so, there may be logs which give an indication as to why `fetchUrl` failed.

**Comment by bcoles** [comment] 2022-05-29 08:02
I suggest not running more than one scan at once.

> 2022-05-28 02:04:46,205 [INFO] sf lib : Running 37 correlation rules.
> 2022-05-28 02:28:34,125 [INFO] sf lib : Scan [089C2113] completed.
> 2022-05-28 02:30:13,018 [INFO] sf lib : Scan [0E601609] completed.)

This output is suspicious.

**Comment by 1Suprem3** [comment] 2022-05-30 11:25
> I suggest not running more than one scan at once.
> 
> > 2022-05-28 02:04:46,205 [INFO] sf lib : Running 37 correlation rules.
> > 2022-05-28 02:28:34,125 [INFO] sf lib : Scan [089C2113] completed.
> > 2022-05-28 02:30:13,018 [INFO] sf lib : Scan [0E601609] completed.)
> 
> This output is suspicious.

Thank you for prompting. Is there a similar error in previous versions?

**Comment by bcoles** [comment] 2022-05-30 11:37
> Is there a similar error in previous versions?

It is not clear what error, if any, has occurred here, apart from the `sfp_spider` issue. PR #1693 addresses the issue in `sfp_spider`, but has not yet been merged.

None of the previous versions support running multiple concurrent scans better than the latest version.

Threading was introduced in version 3.3. If the issue is threading related, then the issue may not exist in versions 3.2 and earlier. However, a lot of bug fixes and improvements have been implemented since 3.2.

> although I understood that this could not be the case (not all goals were met)

What does this mean? What makes you think the scan did not complete?

**Comment by 1Suprem3** [comment] 2022-05-30 11:44
> > Is there a similar error in previous versions?
> 
> It is not clear what error, if any, has occurred here, apart from the `sfp_spider` issue. PR #1693 addresses the issue in `sfp_spider`, but has not yet been merged.
> 
> None of the previous versions support running multiple concurrent scans better than the latest version.
> 
> Threading was introduced in version 3.3. If the issue is threading related, then the issue may not exist in versions 3.2 and earlier. However, a lot of bug fixes and improvements have been implemented since 3.2.
> 
> > although I understood that this could not be the case (not all goals were met)
> 
> What does this mean? What makes you think the scan did not complete?

I was doing a site scan www.bleepingcomputer.com and I was looking specifically for bitcoin and ethereum addresses (I'm doing research). I know that this site has a section with a large number of articles and there is also a section with a forum that includes more than 50 thousand different topics. I checked other sites in a similar way, I got a lot more information there than from this one, although they were much smaller.
Maybe you can give me advice on how to run a scan correctly for my task? It would help me a lot.

**Comment by bcoles** [comment] 2022-05-30 11:58
> > > although I understood that this could not be the case (not all goals were met)
> > 
> > 
> > What does this mean? What makes you think the scan did not complete?
> 
> I was doing a site scan [www.bleepingcomputer.com](http://www.bleepingcomputer.com) and I was looking specifically for bitcoin and ethereum addresses (I'm doing research). I know that this site has a section with a large number of articles and there is also a section with a forum that includes more than 50 thousand different topics. I checked other sites in a similar way, I got a lot more information there than from this one, although they were much smaller.

Ok that makes sense. Yes, if the `sfp_spider` module crashed, then spidering will not have completed, and you will not receive all data.

> Maybe you can give me advice on how to run a scan correctly for my task? It would help me a lot.

You should wait until #1693 is merged, or apply the patch manually.

You may want to adjust the spider settings to increase the maximum number of pages spidered and the spider depth.

![sfp_spider settings](https://user-images.githubusercontent.com/434827/170987562-61f99f7f-08cc-4dd6-8226-147f7b5c0778.png)

In addition to the `sfp_spider` module, you will likely also want to run some content analysis modules, such as these:

* modules/sfp_webanalytics.py
* modules/sfp_hosting.py
* modules/sfp_phone.py
* modules/sfp_ethereum.py
* modules/sfp_hashes.py
* modules/sfp_base64.py
* modules/sfp_bitcoin.py
* modules/sfp_countryname.py
* modules/sfp_creditcard.py
* modules/sfp_email.py
* modules/sfp_iban.py
* modules/sfp_company.py
* modules/sfp_errors.py

It depends what you're looking for.

**Comment by 1Suprem3** [comment] 2022-05-30 12:18
> > > > although I understood that this could not be the case (not all goals were met)
> > > 
> > > 
> > > What does this mean? What makes you think the scan did not complete?
> > 
> > 
> > I was doing a site scan [www.bleepingcomputer.com](http://www.bleepingcomputer.com) and I was looking specifically for bitcoin and ethereum addresses (I'm doing research). I know that this site has a section with a large number of articles and there is also a section with a forum that includes more than 50 thousand different topics. I checked other sites in a similar way, I got a lot more information there than from this one, although they were much smaller.
> 
> Ok that makes sense. Yes, if the `sfp_spider` module crashed, then spidering will not have completed, and you will not receive all data.
> 
> > Maybe you can give me advice on how to run a scan correctly for my task? It would help me a lot.
> 
> You should wait until #1693 is merged, or apply the patch manually.
> 
> You may want to adjust the spider settings to increase the maximum number of pages spidered and the spider depth.
> 
> ![sfp_spider settings](https://user-images.githubusercontent.com/434827/170987562-61f99f7f-08cc-4dd6-8226-147f7b5c0778.png)
> 
> In addition to the `sfp_spider` module, you will likely also want to run some content analysis modules, such as these:
> 
> * modules/sfp_webanalytics.py
> * modules/sfp_hosting.py
> * modules/sfp_phone.py
> * modules/sfp_ethereum.py
> * modules/sfp_hashes.py
> * modules/sfp_base64.py
> * modules/sfp_bitcoin.py
> * modules/sfp_countryname.py
> * modules/sfp_creditcard.py
> * modules/sfp_email.py
> * modules/sfp_iban.py
> * modules/sfp_company.py
> * modules/sfp_errors.py
> 
> It depends what you're looking for.

Thank you so much for the detailed answer, I set the following values:
![image](https://user-images.githubusercontent.com/104645192/170990031-0144af2d-138d-4174-b9af-26e86ce9835c.png)

I would also like to ask another question: can I reduce the size of the stored data of the "sfp__stor_db" module to facilitate scanning or increase the data loading speed? It's just that with a long scan, I can wait for several minutes in order to open the results during the scan. After all, I only need to get the addresses of crypto wallets that are no more than 100 bytes in size.
![image](https://user-images.githubusercontent.com/104645192/170990578-491e68c6-dca2-4912-8aec-5bbfd704625d.png)

And the last question: how can I apply this patch manually? I need to edit the file "sfp_spider.py " manually or can I update it via the linux terminal?

**Comment by bcoles** [comment] 2022-05-30 12:45
> I set the following values:

50,000 scan depth is huge. The scan may run for a very long time.


> I would also like to ask another question: can I reduce the size of the stored data of the "sfp__stor_db" module to facilitate scanning or increase the data loading speed? It's just that with a long scan, I can wait for several minutes in order to open the results during the scan.

That setting is unlikely to reduce the time required to load the scan page. It is unlikely to have much affect on the scan speed either.


> After all, I only need to get the addresses of crypto wallets that are no more than 100 bytes in size.

You can easily extract the addresses from the SQLite database if that's all you're after.

> And the last question: how can I apply this patch manually? I need to edit the file "sfp_spider.py " manually or can I update it via the linux terminal?

If you're using the latest version of SpiderFoot from GitHub, you should be able to replace the `modules/sfp_spider.py` file with the file from the pull request:

https://github.com/smicallef/spiderfoot/blob/1fa956456813d14af254e469d89701b8eb83c4c0/modules/sfp_spider.py

**Comment by bcoles** [comment] 2022-05-30 12:49
If all you want to do is mirror a website and extract bitcoin addresses, it would be significantly more efficient to use the correct tool for the job. Use a spidering tool such as `wget` to mirror the website, and write some custom code to load and pass each mirrored file looking for crypto addresses.

**Closed** 2022-05-31 19:57 UTC
