### ISSUE TITLE
Cherrypy- tools.encode

### ISSUE THREAD

**Issue by cyberlive-debug** [smicallef/spiderfoot#989] opened 2020-09-05 13:10 UTC
We are using the most recent version of Spiderfoot via Docker build and have written several custom modules.  The majority of our custom modules work without any issue but one specifically (built around the Social Searcher API), throws an error when we try and run it. 

We have the docker deployed within AWS - ECR and it runs via their ECS (task definition and services).

The social searcher module loads fine into UI / CLI (via the -M).  When we run it in then UI, it returns the cherry.py encoding error related to Unicode and tools.encode.  

The question; 

Since we are using Docker in the above setup, is this to be addressed via the docker image itself such as the sflib.py...or directly in the global config for cherry.py

Thank you

**Comment by bcoles** [comment] 2020-09-05 13:46
> The social searcher module loads fine into UI / CLI (via the -M). When we run it in then UI, it returns the cherry.py encoding error related to Unicode and tools.encode.

It might help to see the error message or stack trace.

Modules should never result in a cherrpy error being raised. The issue is most likely in the custom module itself, when handling an incoming `event` or storing an `event`.

> We are using the most recent version of Spiderfoot via Docker build and have written several custom modules.

Does the Docker build use the latest 3.2 stable release, or latest 3.3-DEV version from GitHub `master` ?

Version 3.2 introduced a change to the module structure which will have likely broken custom modules. You will need to add a `meta` `dict()` object to start of the module. This replaces the module docstring which is no longer used.

Here's an example from the [sfp_dnsresolve](https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_dnsresolve.py) module:

```python
class sfp_dnsresolve(SpiderFootPlugin):

    meta = {
        'name': "DNS Resolver",
        'summary': "Resolves Hosts and IP Addresses identified, also extracted from raw content.",
        'flags': [""],
        'useCases': ["Footprint", "Investigate", "Passive"],
        'categories': ["DNS"]
    }
```

There have also been a few changes in the core SpiderFoot code recently in 3.3-DEV which will likely have broken custom modules due to changing the import structure.

If you're using 3.3-DEV, the good news is that this should be fairly easy to resolve by fixing the module imports:

```python
from spiderfoot import SpiderFootEvent, SpiderFootPlugin
```

**Comment by cyberlive-debug** [comment] 2020-09-06 11:56
Please see error message / stack trace below;

Unrecoverable error in the server.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/spiderfoot/sfwebui.py", line 900, in startscan
    scanId = sf.genScanInstanceGUID()
AttributeError: 'SpiderFoot' object has no attribute 'genScanInstanceGUID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 604, in run
    self.respond(pi)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 653, in respond
    self.handle_error()
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 766, in handle_error
    self.error_response()
  File "/home/spiderfoot/sfwebui.py", line 81, in error_page
    cherrypy.response.body = '<html><body>Error</body></html>'
  File "/usr/lib/python3.6/site-packages/cherrypy/__init__.py", line 231, in __setattr__
    setattr(child, name, value)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 792, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.

###########################

Docker build is using the current stable release of 3.2 from the Master

We have added the meta dict() object to start of the module but the issue still remains.

Thanks for the feedback

**Comment by bcoles** [comment] 2020-09-06 12:38
There's a couple of errors here. The cherrypy issue is due to a failure to encode the error message. The root cause of the error message is here:

```
File "/home/spiderfoot/sfwebui.py", line 900, in startscan
scanId = sf.genScanInstanceGUID()
```

> Docker build is using the current stable release of 3.2 from the Master

Did you build the docker image yourself?

I'm not sure what version you're using, but it is not the [3.2 release](https://github.com/smicallef/spiderfoot/releases), it is not the tagged [v3.2 branch release branch](https://github.com/smicallef/spiderfoot/tree/v3.2), and it is not the current 3.3-DEV version on `master`. None of these versions contains that line of code.

The `master` branch is 3.3-DEV, and doesn't include any instances of `genScanInstanceGUID` anywhere, as this function was renamed from `genScanInstanceGUID` to `genScanInstanceId` in commit df92f7db6bab18360aca3eab0219f8b005f92627 on August 22.

The 3.2 release was released on August 31.

Just to be sure, I downloaded the 3.2 release to take a look, and `scanId = sf.genScanInstanceGUID()` is not present in `sfwebui.py`.

I suggest using the [3.2 release](https://github.com/smicallef/spiderfoot/releases) for your docker build.

**Comment by cyberlive-debug** [comment] 2020-09-06 12:48
Thanks for the additional feedback.  

We’ll keep digging here and update accordingly.  We grabbed the version from github and simply deployed it in AWS ECR and run it in AWS ECS. 

Not sure what the underlying issue with the docker image would be as everything runs fine via the UI and CLI for the rest of Spiderfoot, with the exception of this one custom module.  

We’ll redeploy with 3.2 via a new ECR, etc. And post the results.

**Comment by smicallef** [comment] 2020-10-14 05:10
Any update on this, or can I close this bug?

**Comment by cyberlive-debug** [comment] 2020-10-14 12:08
Please close.  We recreated it within AWS two different occasions but had the same results

**Closed** 2021-07-14 07:37 UTC
Labels: investigate
