### ISSUE TITLE
Persistent error when running scans

### ISSUE THREAD

**Issue by DuKe27612** [smicallef/spiderfoot#656] opened 2020-07-29 13:45 UTC
Hi everyone, 

This error appeared in multiple scans yesterday.  Completely willing to believe this is a mis-configuration on my side, but just in case someone else reported it, here ya go.

Unhandled exception (error) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_badipscom.pyc", line 246, in handleEvent\n', '  File "modules\\sfp_badipscom.pyc", line 197, in lookupItem\n', '  File "modules\\sfp_badipscom.pyc", line 182, in resourceList\n', '  File "re.pyc", line 141, in match\n', '  File "re.pyc", line 251, in _compile\n', 'error: nothing to repeat\n']

**Comment by bcoles** [comment] 2020-07-29 13:46
Are you using the latest release version 3.0 or the latest version from GitHub `master` branch?

**Comment by bcoles** [comment] 2020-07-29 13:52
It looks like this is probably a bug with the format string.

```python
   'badips.com IP Reptutation List': {
        'id': '_badips',
        'type': 'list',
        'checks': ['ip', 'domain'],
        'url': 'https://www.badips.com/get/list/any/1?age=24h',
        'regex': '{0}'
    }

# ...
                else:
                    # Check for the domain and the hostname
                    try:
                        rxDom = str(malchecks[check]['regex']).format(targetDom)
                        rxTgt = str(malchecks[check]['regex']).format(target)
```

**Comment by bcoles** [comment] 2020-07-29 14:16
Thanks for the report. This module is old and needs a rewrite.

I wasn't able to reproduce this issue, but hopefully it will be fixed when the module is rewritten.

**Closed** 2020-07-31 05:06 UTC
