### ISSUE TITLE
spiderfoot runs properly, but scans tab never stops "loading"

### ISSUE THREAD

**Issue by vlogkeeper** [smicallef/spiderfoot#536] opened 2020-05-23 03:14 UTC
I run spiderfoot with no errors (in python term), upon visiting the website there is an infinitely long loading screen, the "new scan" and "settings" button both work, but when making a scan it redirects to another page that loads forever and none of the buttons work other than the "new scan" and "settings"...

**Comment by vlogkeeper** [comment] 2020-05-23 03:15
![image](https://user-images.githubusercontent.com/52940827/82720486-ac111d00-9c79-11ea-94d4-33605ab2a82b.png)
![image](https://user-images.githubusercontent.com/52940827/82720494-bdf2c000-9c79-11ea-925a-620cf1be3459.png)

**Comment by bcoles** [comment] 2020-05-23 03:25
Do you get errors in the browser console?

**Comment by vlogkeeper** [comment] 2020-05-23 03:30
I seem to be getting the error "sf is not defined"
![image](https://user-images.githubusercontent.com/52940827/82720726-de237e80-9c7b-11ea-9979-c342e7942adf.png)

**Comment by bcoles** [comment] 2020-07-11 08:52
Looks like a dupe of #511 which was a dupe of #471 which turned out to be a dependency issue.

Ensure you're using Python3 and have installed the appropriate dependencies with `pip3`.

```
pip3 install -r requirements.txt
python3 ./sf.py -l 127.0.0.1:3000
```

If the problem persists, updating CherryPy might help:

```
pip3 install cherrypy --upgrade
```

**Comment by dpeeke** [comment] 2020-07-28 21:11
I was experiencing this exact issue running on Windows, this work around resolved it for me:

Open regedit.exe

Browse to key: HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.js
Change value of "Content Type" to "application/javascript"

Originally the value was set to "text/plain".

**Closed** 2020-09-08 18:23 UTC
