### ISSUE TITLE
Received an Error While Attempting to Scan

### ISSUE THREAD

**Issue by bjmaynard01** [smicallef/spiderfoot#60] opened 2015-03-12 16:15 UTC
![image](https://cloud.githubusercontent.com/assets/463486/6622166/68f8c4ec-c8b1-11e4-9e44-9ebdb0ad87b2.png)

**Comment by smicallef** [comment] 2015-03-12 21:36
Do you have Internet connectivity? From the same machine SpiderFoot is running on, try and fetch: http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1

SpiderFoot needs that to work, so if it cannot fetch it, you'll get the above error.

**Comment by asohoni** [comment] 2015-04-13 09:43
Hello All,
I am facing the same exact issue while trying to initiate a scan. Also I did try to access the above URL and it seems its moved permanently (301 status code) to a new location as ,

https://publicsuffix.org/list/effective_tld_names.dat

that might be a reason, why spiderfoot is unable to fetch the required data.
Can you please suggest what changes shall I go ahead with on this.

**Comment by Gormogon** [comment] 2015-04-13 12:38
@asohoni thanks for being proactive and reporting this.  I believe this issue was resolved with 36fbdd0b760c3d74e5dce40e1fbd2b5b3caf8218 and you should see this take effect with the next upcoming stable release.  In the meantime, I would encourage you to clone the repo and run your scan again with the dev code to see if you receive the same error.

**Comment by asohoni** [comment] 2015-04-13 13:06
@Gormogon thanks for the prompt response on the above, I have made the changes as per 
'36fbdd0', but when running with updated code, I am unable to see the changes on my local, its still fetching from the wrong path URL.

**Comment by asohoni** [comment] 2015-04-13 13:19
![capture](https://cloud.githubusercontent.com/assets/11922413/7116254/c952488e-e20d-11e4-90a9-ac83a8ad802c.JPG)

Attached is the error I am facing, for your reference.

**Comment by Gormogon** [comment] 2015-04-13 13:47
@asohoni you now appear to be going to the correct URL.  However, the error you are receiving is a Connection Refused error, meaning that this is most likely caused by a networking error rather than an issue in the code.

This post provides an excellent explanation: http://stackoverflow.com/questions/12145536/how-can-i-debug-what-is-causing-a-connection-refused-or-a-connection-time-out

**Closed** 2015-08-23 19:50 UTC
